[CmdletBinding()]
param([Parameter(Mandatory)][string]$Simfile,[Parameter(Mandatory)][string]$Preview,[Parameter(Mandatory)][switch]$Approved,[string]$FallbackOriginal,[int]$Width=836,[int]$Height=328)
$ErrorActionPreference='Stop'; if(-not $Approved){throw 'Explicit -Approved is required after owner approval of the exact preview.'}
$inspect=& (Join-Path $PSScriptRoot 'Inspect-Banner.ps1') -Simfile $Simfile -AllowMissing; $source=(Resolve-Path -LiteralPath $Preview).Path; $target=$inspect.BannerPath; $beforeReference=$inspect.BannerReference; $targetExisted=Test-Path -LiteralPath $target -PathType Leaf
$backupSource=$target
if(-not $targetExisted){if([string]::IsNullOrWhiteSpace($FallbackOriginal)){throw 'The referenced banner is missing; -FallbackOriginal is required for a recoverable installation.'};$fallback=(Resolve-Path -LiteralPath $FallbackOriginal).Path;$songRoot=[IO.Path]::GetFullPath((Split-Path -Parent $inspect.Simfile)).TrimEnd('\')+'\';if(-not $fallback.StartsWith($songRoot,[StringComparison]::OrdinalIgnoreCase)){throw 'Fallback original is outside the song directory.'};$backupSource=$fallback}
$stamp=Get-Date -Format 'yyyyMMdd-HHmmss'; $backup="$target.pre-upscale-$stamp.bak"; $temp=Join-Path (Split-Path -Parent $target) ('.banner-install-'+[guid]::NewGuid().ToString('N')+'.png')
Add-Type -AssemblyName System.Drawing; $input=[Drawing.Image]::FromFile($source)
try{$bitmap=New-Object Drawing.Bitmap $Width,$Height,([Drawing.Imaging.PixelFormat]::Format32bppArgb);try{$g=[Drawing.Graphics]::FromImage($bitmap);try{$g.CompositingQuality=[Drawing.Drawing2D.CompositingQuality]::HighQuality;$g.InterpolationMode=[Drawing.Drawing2D.InterpolationMode]::HighQualityBicubic;$g.DrawImage($input,0,0,$Width,$Height);$bitmap.Save($temp,[Drawing.Imaging.ImageFormat]::Png)}finally{$g.Dispose()}}finally{$bitmap.Dispose()}}finally{$input.Dispose()}
try{Copy-Item -LiteralPath $backupSource -Destination $backup;Move-Item -LiteralPath $temp -Destination $target -Force;$after=& (Join-Path $PSScriptRoot 'Inspect-Banner.ps1') -Simfile $Simfile;if($after.Width-ne$Width-or$after.Height-ne$Height){throw 'Installed PNG dimensions failed validation.'};if($after.BannerReference-cne$beforeReference){throw '#BANNER reference changed unexpectedly.'};[pscustomobject]@{Installed=$target;Backup=$backup;BackupSource=$backupSource;CreatedMissingTarget=(-not $targetExisted);Width=$after.Width;Height=$after.Height;BannerReference=$after.BannerReference;RestartedITGmania=$false}}catch{if($targetExisted-and(Test-Path -LiteralPath $backup)){Copy-Item -LiteralPath $backup -Destination $target -Force}elseif((-not $targetExisted)-and(Test-Path -LiteralPath $target)){Remove-Item -LiteralPath $target -Force};throw}finally{if(Test-Path -LiteralPath $temp){Remove-Item -LiteralPath $temp -Force}}
