[CmdletBinding()]
param([Parameter(Mandatory)][string]$Simfile)
$ErrorActionPreference='Stop'; $sim=(Resolve-Path -LiteralPath $Simfile).Path; $song=Split-Path -Parent $sim; $references=@()
$simfiles=@(Get-ChildItem -LiteralPath $song -File|Where-Object Extension -in @('.sm','.ssc')|Sort-Object Name);if($simfiles.Count-eq 0){throw 'No .sm or .ssc simfile found.'}
foreach($candidateSim in $simfiles){$text=[IO.File]::ReadAllText($candidateSim.FullName);if([regex]::IsMatch($text,'(?im)^#BGCHANGES\s*:')){throw "Songs with BGCHANGES are excluded: $($candidateSim.Name)"};$matches=[regex]::Matches($text,'(?im)^#BACKGROUND\s*:\s*([^;\r\n]+)\s*;');if($matches.Count-ne 1){throw "Expected exactly one explicit #BACKGROUND reference in $($candidateSim.Name); found $($matches.Count)."};$references+=$matches[0].Groups[1].Value.Trim()}
$unique=@($references|Sort-Object -Unique);if($unique.Count-ne 1){throw 'Simfiles disagree on #BACKGROUND.'};$reference=$unique[0];$extension=[IO.Path]::GetExtension($reference).ToLowerInvariant(); if($extension-notin @('.png','.jpg','.jpeg','.bmp')){throw "Unsupported or non-static background extension: $extension"}
$target=[IO.Path]::GetFullPath((Join-Path $song $reference)); $root=[IO.Path]::GetFullPath($song).TrimEnd('\')+'\'; if(-not $target.StartsWith($root,[StringComparison]::OrdinalIgnoreCase)){throw '#BACKGROUND resolves outside the song directory.'}; if(-not(Test-Path -LiteralPath $target -PathType Leaf)){throw 'Referenced background does not exist.'}
Add-Type -AssemblyName System.Drawing; $img=[Drawing.Image]::FromFile($target)
try{$dimension=New-Object Drawing.Imaging.FrameDimension($img.FrameDimensionsList[0]);$frames=$img.GetFrameCount($dimension);if($frames-ne 1){throw "Animated or multi-frame background is excluded; found $frames frames."};[pscustomobject]@{Simfile=$sim;BackgroundReference=$reference;BackgroundPath=$target;Width=$img.Width;Height=$img.Height;FrameCount=$frames;Extension=$extension;Format=$img.RawFormat.ToString()}}finally{$img.Dispose()}
