[CmdletBinding()]
param([string]$PackPath='C:\Games\ITGmania\Songs\Misc. Collected',[string]$QueuePath,[switch]$Refresh,[switch]$SelectNext,[switch]$ReturnToQueue,[switch]$AwaitOwnerInput,[ValidateSet('eligible','pending','installed','denied','skipped')][string]$SetStatus,[string]$SongPath,[string]$Fingerprint,[string]$PreviewPath,[ValidateSet('generation-failed','output-handling-error','prompt-error','preview-rejected','new-source-supplied')][string]$AttemptOutcome,[string]$AttemptNote,[string]$DecisionNote,[int]$LockTimeoutSeconds=60)
$ErrorActionPreference='Stop';$repo=Split-Path -Parent (Split-Path -Parent (Split-Path -Parent (Split-Path -Parent $PSScriptRoot)));if(-not $QueuePath){$QueuePath=Join-Path $repo 'memory\background-upscale-queue.json'};$statuses=@('eligible','ineligible','review-only','pending','installed','denied','skipped')
function Hash([string]$p){(Get-FileHash -LiteralPath $p -Algorithm SHA256).Hash}
function Rel([string]$base,[string]$child){$b=[IO.Path]::GetFullPath($base).TrimEnd('\')+'\';$c=[IO.Path]::GetFullPath($child);if(-not$c.StartsWith($b,[StringComparison]::OrdinalIgnoreCase)){throw "Path outside base: $c"};$c.Substring($b.Length).Replace('\','/')}
function ImageInfo([string]$p){Add-Type -AssemblyName System.Drawing;try{$i=[Drawing.Image]::FromFile($p);try{$d=New-Object Drawing.Imaging.FrameDimension($i.FrameDimensionsList[0]);[pscustomobject]@{Width=$i.Width;Height=$i.Height;Frames=$i.GetFrameCount($d)}}finally{$i.Dispose()}}catch{$null}}
function BgState([string]$text){$markers=[regex]::Matches($text,'(?im)^#BGCHANGES\s*:');if($markers.Count -eq 0){return 'none'};$tags=[regex]::Matches($text,'(?is)#BGCHANGES\s*:(.*?);');if($tags.Count -ne $markers.Count){return 'malformed'};foreach($tag in $tags){if(-not[string]::IsNullOrWhiteSpace($tag.Groups[1].Value)){return 'populated'}};'empty'}
function Quality([int]$width,[int]$height){$ratio=$width/[math]::Max(1,$height);$off=[math]::Abs($ratio-(16/9))-gt.02;$low=$width-lt1920-or$height-lt1080;if($width-lt640-or$height-lt360){$rank=0;$tier='broken-or-tiny'}elseif($off){$rank=1;$tier='aspect-mismatch'}elseif($width-le854-or$height-le480){$rank=2;$tier='sd-or-smaller'}elseif($width-lt1280-or$height-lt720){$rank=3;$tier='sub-hd'}else{$rank=4;$tier='soft-review'};[pscustomobject]@{Eligible=$low-or$off;Low=$low;Off=$off;Rank=$rank;Tier=$tier}}
function ReviewCandidates([IO.DirectoryInfo]$song){$items=@();foreach($file in Get-ChildItem -LiteralPath $song.FullName -File|Sort-Object Name){$ext=$file.Extension.ToLowerInvariant();if($ext -notin @('.png','.jpg','.jpeg','.bmp')){continue};$stem=[IO.Path]::GetFileNameWithoutExtension($file.Name);if($stem -match '(?i)banner' -or $stem -notmatch '(?i)(?:^|[-_.\s])(bg|background)(?:$|[-_.\s])'){continue};$info=ImageInfo $file.FullName;if(-not$info -or $info.Frames -ne 1){continue};$items+=[pscustomobject][ordered]@{path=Rel $song.FullName $file.FullName;sha256=Hash $file.FullName;width=$info.Width;height=$info.Height;frames=$info.Frames;extension=$ext}};@($items)}
function WriteDoc($d,[string]$p){$tmp="$p.$([guid]::NewGuid().ToString('N')).tmp";try{[IO.File]::WriteAllText($tmp,($d|ConvertTo-Json -Depth 10)+"`n",[Text.UTF8Encoding]::new($false));Move-Item -LiteralPath $tmp -Destination $p -Force}finally{if(Test-Path -LiteralPath $tmp){Remove-Item -LiteralPath $tmp -Force}}}
function ContentKey($record){$simKey=@($record.simfiles|ForEach-Object{"$($_.path):$($_.sha256)"})-join'|';$legacyKey=if($record.PSObject.Properties.Name-contains'legacyFiles'){@($record.legacyFiles|ForEach-Object{"$($_.path):$($_.sha256)"})-join'|'}else{''};@($record.backgroundReference,$record.sourcePath,$record.sourceSha256,$simKey,$legacyKey)-join"`n"}
function Assess([IO.DirectoryInfo]$song,[string]$root,[string]$now){
 $relative=Rel $root $song.FullName;$sims=@(Get-ChildItem -LiteralPath $song.FullName -File|Where-Object Extension -in @('.sm','.ssc')|Sort-Object Name);$dwis=@(Get-ChildItem -LiteralPath $song.FullName -File|Where-Object Extension -eq '.dwi'|Sort-Object Name);$refs=@();$allRefsExplicit=$true;$parts=@();$dwiParts=@();$states=@()
 foreach($s in $sims){$t=[IO.File]::ReadAllText($s.FullName);$states+=BgState $t;$m=[regex]::Matches($t,'(?im)^#BACKGROUND\s*:\s*([^;\r\n]+)\s*;');if($m.Count-eq1){$refs+=$m[0].Groups[1].Value.Trim()}else{$allRefsExplicit=$false};$parts+="$($s.Name):$(Hash $s.FullName)"}
 foreach($dwi in $dwis){$dwiParts+="$($dwi.Name):$(Hash $dwi.FullName)"}
 $bgState=if($states -contains 'malformed'){'malformed'}elseif($states -contains 'populated'){'populated'}elseif($states -contains 'empty'){'empty'}else{'none'}
 $u=@($refs|Where-Object{$_}|Sort-Object -Unique);$ref=if($u.Count-eq1-and$allRefsExplicit){$u[0]}else{$null};$path=$null;$info=$null;$reason=$null;$eligible=$false;$status='ineligible';$reviewCategory=$null;$review=@();$qualityRank=$null;$qualityTier=$null
 if($sims.Count-eq0){$review=@(ReviewCandidates $song);if($dwis.Count-gt0-and$review.Count-gt0){$status='review-only';$reviewCategory='implicit-legacy';$reason="Legacy DWI content has $($review.Count) plausible static background candidate(s) but no explicit #BACKGROUND; owner source confirmation is required."}else{$reason='No .sm or .ssc file and no reviewable legacy static background candidate.'}}
 elseif($bgState -eq 'malformed'){$reason='BGCHANGES metadata is malformed or unterminated; dynamic behavior cannot be ruled out.'}
 elseif($bgState -eq 'populated'){$reason='BGCHANGES contains active content; changing or animated backgrounds are excluded.'}
 elseif(-not$ref){$review=@(ReviewCandidates $song);if($review.Count-gt0){$status='review-only';$reviewCategory='implicit-legacy';$reason="Missing, ambiguous, or inconsistent explicit #BACKGROUND; $($review.Count) plausible static candidate(s) require owner source confirmation."}else{$reason='Missing, ambiguous, or inconsistent explicit #BACKGROUND reference.'}}
 else{$ext=[IO.Path]::GetExtension($ref).ToLowerInvariant();if($ext -notin @('.png','.jpg','.jpeg','.bmp')){$reason="Unsupported or non-static extension: $ext"}else{$candidate=[IO.Path]::GetFullPath((Join-Path $song.FullName $ref));$songRoot=[IO.Path]::GetFullPath($song.FullName).TrimEnd('\')+'\';if(-not$candidate.StartsWith($songRoot,[StringComparison]::OrdinalIgnoreCase)){$reason='#BACKGROUND resolves outside the song directory.'}elseif(-not(Test-Path -LiteralPath $candidate -PathType Leaf)){$review=@(ReviewCandidates $song|Where-Object{$_.path -ne $ref});if($review.Count -gt 0){$status='review-only';$reviewCategory='missing-reference-fallback';$reason="Referenced background is missing; $($review.Count) plausible contained fallback candidate(s) require owner source confirmation."}else{$reason='Referenced background is missing.'}}else{$path=$candidate;$info=ImageInfo $path;if(-not$info){$reason='Referenced background does not decode.'}elseif($info.Frames -ne 1){$reason='Animated or multi-frame background is excluded.'}else{$quality=Quality $info.Width $info.Height;$eligible=$quality.Eligible;$qualityRank=$quality.Rank;$qualityTier=$quality.Tier;$status=if($eligible){'eligible'}else{'ineligible'};$reason=if($quality.Off){'Static background is not 16:9 and needs fit review.'}elseif($quality.Low){'Static background is below 1920 x 1080 and needs quality review.'}else{'Static background meets the 1920 x 1080 16:9 baseline.'}}}}}
 if(-not$path-and$u.Count-eq1){$factRef=$u[0];$factExt=[IO.Path]::GetExtension($factRef).ToLowerInvariant();if($factExt-in@('.png','.jpg','.jpeg','.bmp')){$factCandidate=[IO.Path]::GetFullPath((Join-Path $song.FullName $factRef));$factRoot=[IO.Path]::GetFullPath($song.FullName).TrimEnd('\')+'\';if($factCandidate.StartsWith($factRoot,[StringComparison]::OrdinalIgnoreCase)-and(Test-Path -LiteralPath $factCandidate -PathType Leaf)){$factInfo=ImageInfo $factCandidate;if($factInfo-and$factInfo.Frames-eq1){$path=$factCandidate;$info=$factInfo}}}}
 $srcRel=if($path){Rel $song.FullName $path}else{$null};$srcHash=if($path){Hash $path}else{$null};$reviewKey=@($review|ForEach-Object{"$($_.path):$($_.sha256)"})-join'|';$raw=@($relative,($parts-join'|'),($dwiParts-join'|'),$bgState,$ref,$srcRel,$srcHash,$reviewCategory,$reviewKey,$qualityRank,$qualityTier,$reason)-join"`n";$sha=[Security.Cryptography.SHA256]::Create();try{$fp=([BitConverter]::ToString($sha.ComputeHash([Text.Encoding]::UTF8.GetBytes($raw)))).Replace('-','')}finally{$sha.Dispose()}
 [ordered]@{songPath=$relative;fingerprint=$fp;simfiles=@($parts|ForEach-Object{$n,$h=$_-split':',2;[ordered]@{path=$n;sha256=$h}});legacyFiles=@($dwiParts|ForEach-Object{$n,$h=$_-split':',2;[ordered]@{path=$n;sha256=$h}});bgChangesState=$bgState;backgroundReference=$ref;sourcePath=$srcRel;sourceSha256=$srcHash;sourceWidth=if($info){$info.Width}else{$null};sourceHeight=if($info){$info.Height}else{$null};sourceFrames=if($info){$info.Frames}else{$null};qualityRank=$qualityRank;qualityTier=$qualityTier;reviewCategory=$reviewCategory;reviewCandidates=@($review);observedAt=$now;assessedAt=$now;eligible=$eligible;reason=$reason;status=$status;processedAt=$null;lastAttemptedAt=$null;pendingAction=$null;previewPath=$null;previewSha256=$null;attemptHistory=@();decisionHistory=@()}
}
$pack=(Resolve-Path -LiteralPath $PackPath).Path;$file=[IO.Path]::GetFullPath($QueuePath)
$lockHash=[Security.Cryptography.SHA256]::Create();try{$lockBytes=[Text.Encoding]::UTF8.GetBytes($file.ToLowerInvariant());$lockId=([BitConverter]::ToString($lockHash.ComputeHash($lockBytes))).Replace('-','')}finally{$lockHash.Dispose()}
$queueMutex=[Threading.Mutex]::new($false,"Local\ThraxOS-BackgroundQueue-$lockId");$queueLockTaken=$false
try{
try{$queueLockTaken=$queueMutex.WaitOne([TimeSpan]::FromSeconds($LockTimeoutSeconds))}catch [Threading.AbandonedMutexException]{$queueLockTaken=$true}
if(-not$queueLockTaken){throw "Timed out waiting for the background queue lock: $file"}
$doc=if(Test-Path -LiteralPath $file){[IO.File]::ReadAllText($file,[Text.UTF8Encoding]::new($false))|ConvertFrom-Json}else{[pscustomobject]@{schemaVersion=2;packPath='C:\Games\ITGmania\Songs\Misc. Collected';generatedAt=$null;songs=@();learningHistory=@()}}
if($Refresh){$now=(Get-Date).ToUniversalTime().ToString('o');$old=@{};foreach($x in @($doc.songs)){$old[$x.songPath]=$x};$songs=@();$changed=[int]$doc.schemaVersion-ne2;foreach($dir in Get-ChildItem -LiteralPath $pack -Directory|Sort-Object Name){$fresh=Assess $dir $pack $now;$prior=$old[$fresh.songPath];if($prior-and$prior.fingerprint-eq$fresh.fingerprint){if($prior.status-notin$statuses){throw "Invalid status: $($prior.status)"};$songs+=$prior}elseif($prior-and$prior.status-eq'installed'-and$prior.previewSha256-and$prior.previewSha256-eq$fresh.sourceSha256){$fresh.status='installed';$fresh.eligible=$false;$fresh.reason='Current source exactly matches the previously approved installed preview.';$fresh.processedAt=$prior.processedAt;$fresh.lastAttemptedAt=$prior.lastAttemptedAt;$fresh.previewPath=$prior.previewPath;$fresh.previewSha256=$prior.previewSha256;$fresh.attemptHistory=@($prior.attemptHistory);$fresh.decisionHistory=@($prior.decisionHistory);$songs+=[pscustomobject]$fresh;$changed=$true}elseif($prior-and$prior.status -in @('eligible','pending','skipped','denied')-and(ContentKey $prior) -eq (ContentKey ([pscustomobject]$fresh))){$fresh.status=$prior.status;$fresh.processedAt=$prior.processedAt;$fresh.lastAttemptedAt=$prior.lastAttemptedAt;$fresh.pendingAction=$prior.pendingAction;$fresh.previewPath=$prior.previewPath;$fresh.previewSha256=$prior.previewSha256;$fresh.attemptHistory=@($prior.attemptHistory);$fresh.decisionHistory=@($prior.decisionHistory);$songs+=[pscustomobject]$fresh;$changed=$true}else{$songs+=[pscustomobject]$fresh;$changed=$true}};if(@($doc.songs).Count-ne$songs.Count){$changed=$true};if($changed){$learning=if($doc.PSObject.Properties.Name-contains'learningHistory'){@($doc.learningHistory)}else{@()};$doc=[pscustomobject][ordered]@{schemaVersion=2;packPath='C:\Games\ITGmania\Songs\Misc. Collected';generatedAt=$now;songs=$songs;learningHistory=$learning};WriteDoc $doc $file}}
function Exact(){if(-not$SongPath-or-not$Fingerprint){throw 'SongPath and Fingerprint are required.'};$m=@($doc.songs|Where-Object{$_.songPath-eq$SongPath-and$_.fingerprint-eq$Fingerprint});if($m.Count-ne 1){throw 'Exact current fingerprint not found.'};$m[0]}
if($SetStatus){$r=Exact;if($SetStatus-eq'pending'-and$r.status-notin@('eligible','pending')){throw 'Only eligible content can become pending.'};if($SetStatus-in@('installed','denied')-and$r.status-ne'pending'){throw 'Only pending content can receive an install or denial decision.'};if($SetStatus-eq'skipped'-and$r.status-notin@('eligible','pending')){throw 'Only eligible or pending content can be skipped.'};if($SetStatus-in@('installed','denied','skipped')-and[string]::IsNullOrWhiteSpace($DecisionNote)){throw 'DecisionNote is required.'};if($PreviewPath){$p=(Resolve-Path -LiteralPath $PreviewPath).Path;$r.previewPath=$p;$r.previewSha256=Hash $p};if($SetStatus-in@('installed','denied')-and-not$r.previewSha256){throw 'A bound preview is required.'};$now=(Get-Date).ToUniversalTime().ToString('o');$r.status=$SetStatus;$r.processedAt=if($SetStatus-eq'eligible'){$null}else{$now};if($SetStatus-eq'pending'){$r.lastAttemptedAt=$now};$r.pendingAction=if($SetStatus-eq'pending'-and$r.previewSha256){'awaiting-install-decision'}elseif($SetStatus-eq'pending'){'generate-preview'}else{$null};if($SetStatus-in@('installed','denied','skipped')){$r.decisionHistory=@($r.decisionHistory)+[pscustomobject][ordered]@{recordedAt=$now;outcome=$SetStatus;note=$DecisionNote.Trim();previewPath=$r.previewPath;previewSha256=$r.previewSha256}};$doc.generatedAt=$now;WriteDoc $doc $file}
if($ReturnToQueue){if($SetStatus-or$AwaitOwnerInput){throw 'Cannot combine ReturnToQueue with SetStatus or AwaitOwnerInput.'};$r=Exact;if($r.status-ne'pending'){throw 'Only pending content can be returned.'};if(-not$AttemptOutcome-or[string]::IsNullOrWhiteSpace($AttemptNote)){throw 'AttemptOutcome and AttemptNote are required.'};$now=(Get-Date).ToUniversalTime().ToString('o');$r.attemptHistory=@($r.attemptHistory)+[pscustomobject][ordered]@{recordedAt=$now;outcome=$AttemptOutcome;note=$AttemptNote.Trim();discardedPreviewPath=$r.previewPath;discardedPreviewSha256=$r.previewSha256};$r.lastAttemptedAt=$now;$r.status='eligible';$r.processedAt=$null;$r.pendingAction=$null;$r.previewPath=$null;$r.previewSha256=$null;$doc.generatedAt=$now;WriteDoc $doc $file}
if($AwaitOwnerInput){if($SetStatus-or$ReturnToQueue){throw 'Cannot combine AwaitOwnerInput with SetStatus or ReturnToQueue.'};$r=Exact;if($r.status-ne'pending'){throw 'Only pending content can await owner input.'};if(-not$AttemptOutcome-or[string]::IsNullOrWhiteSpace($AttemptNote)){throw 'AttemptOutcome and AttemptNote are required.'};$now=(Get-Date).ToUniversalTime().ToString('o');$r.attemptHistory=@($r.attemptHistory)+[pscustomobject][ordered]@{recordedAt=$now;outcome=$AttemptOutcome;note=$AttemptNote.Trim();discardedPreviewPath=$r.previewPath;discardedPreviewSha256=$r.previewSha256};$r.lastAttemptedAt=$now;$r.processedAt=$now;$r.pendingAction='awaiting-fallback-approval';$r.previewPath=$null;$r.previewSha256=$null;$doc.generatedAt=$now;WriteDoc $doc $file}
if($SelectNext){$n=@($doc.songs|Where-Object{$_.eligible-and$_.status-eq'eligible'}|Sort-Object @{Expression={if($null-ne$_.qualityRank){[int]$_.qualityRank}else{99}}},@{Expression={if($_.lastAttemptedAt){1}else{0}}},@{Expression={if($_.lastAttemptedAt){[datetime]$_.lastAttemptedAt}else{[datetime]::MinValue}}},@{Expression={[datetime]$_.observedAt}},songPath|Select-Object -First 1);if($n.Count){$n[0]|ConvertTo-Json -Depth 12}else{[pscustomobject]@{result='no-candidates'}|ConvertTo-Json}}else{$counts=@($doc.songs)|Group-Object status|Sort-Object Name|ForEach-Object{[pscustomobject]@{status=$_.Name;count=$_.Count}};[pscustomobject]@{queuePath=$file;total=@($doc.songs).Count;counts=$counts}|ConvertTo-Json -Depth 4}
}finally{if($queueLockTaken){$queueMutex.ReleaseMutex()};$queueMutex.Dispose()}
