[CmdletBinding()]
param([string]$PackPath='C:\Games\ITGmania\Songs\Misc. Collected',[string]$QueuePath,[switch]$Refresh,[switch]$SelectNext,[switch]$ReturnToQueue,[ValidateSet('eligible','pending','installed','denied','skipped')][string]$SetStatus,[string]$SongPath,[string]$Fingerprint,[string]$PreviewPath,[ValidateSet('generation-failed','output-handling-error','prompt-error','preview-rejected','new-source-supplied')][string]$AttemptOutcome,[string]$AttemptNote,[string]$DecisionNote)
$ErrorActionPreference='Stop';$repo=Split-Path -Parent (Split-Path -Parent (Split-Path -Parent (Split-Path -Parent $PSScriptRoot)));if(-not $QueuePath){$QueuePath=Join-Path $repo 'memory\background-upscale-queue.json'};$statuses=@('eligible','ineligible','pending','installed','denied','skipped')
function Hash([string]$p){(Get-FileHash -LiteralPath $p -Algorithm SHA256).Hash}
function Rel([string]$base,[string]$child){$b=[IO.Path]::GetFullPath($base).TrimEnd('\')+'\';$c=[IO.Path]::GetFullPath($child);if(-not$c.StartsWith($b,[StringComparison]::OrdinalIgnoreCase)){throw "Path outside base: $c"};$c.Substring($b.Length).Replace('\','/')}
function ImageInfo([string]$p){Add-Type -AssemblyName System.Drawing;try{$i=[Drawing.Image]::FromFile($p);try{$d=New-Object Drawing.Imaging.FrameDimension($i.FrameDimensionsList[0]);[pscustomobject]@{Width=$i.Width;Height=$i.Height;Frames=$i.GetFrameCount($d)}}finally{$i.Dispose()}}catch{$null}}
function WriteDoc($d,[string]$p){$tmp="$p.$([guid]::NewGuid().ToString('N')).tmp";try{[IO.File]::WriteAllText($tmp,($d|ConvertTo-Json -Depth 10)+"`n",[Text.UTF8Encoding]::new($false));Move-Item -LiteralPath $tmp -Destination $p -Force}finally{if(Test-Path -LiteralPath $tmp){Remove-Item -LiteralPath $tmp -Force}}}
function Assess([IO.DirectoryInfo]$song,[string]$root,[string]$now){
 $relative=Rel $root $song.FullName;$sims=@(Get-ChildItem -LiteralPath $song.FullName -File|Where-Object Extension -in @('.sm','.ssc')|Sort-Object Name);$refs=@();$parts=@();$hasChanges=$false
 foreach($s in $sims){$t=[IO.File]::ReadAllText($s.FullName);if([regex]::IsMatch($t,'(?im)^#BGCHANGES\s*:')){$hasChanges=$true};$m=[regex]::Matches($t,'(?im)^#BACKGROUND\s*:\s*([^;\r\n]+)\s*;');$refs+=if($m.Count-eq 1){$m[0].Groups[1].Value.Trim()}else{$null};$parts+="$($s.Name):$(Hash $s.FullName)"}
 $u=@($refs|Where-Object{$_}|Sort-Object -Unique);$ref=if($u.Count-eq 1-and$refs.Count-eq$sims.Count){$u[0]}else{$null};$path=$null;$info=$null;$reason=$null;$eligible=$false
 if($sims.Count-eq 0){$reason='No .sm or .ssc file.'}elseif($hasChanges){$reason='BGCHANGES is present; animated or changing backgrounds are excluded.'}elseif(-not$ref){$reason='Missing, ambiguous, or inconsistent explicit #BACKGROUND reference.'}else{$ext=[IO.Path]::GetExtension($ref).ToLowerInvariant();if($ext-notin @('.png','.jpg','.jpeg','.bmp')){$reason="Unsupported or non-static extension: $ext"}else{$candidate=[IO.Path]::GetFullPath((Join-Path $song.FullName $ref));$songRoot=[IO.Path]::GetFullPath($song.FullName).TrimEnd('\')+'\';if(-not$candidate.StartsWith($songRoot,[StringComparison]::OrdinalIgnoreCase)){$reason='#BACKGROUND resolves outside the song directory.'}elseif(-not(Test-Path -LiteralPath $candidate -PathType Leaf)){$reason='Referenced background is missing.'}else{$path=$candidate;$info=ImageInfo $path;if(-not$info){$reason='Referenced background does not decode.'}elseif($info.Frames-ne 1){$reason='Animated or multi-frame background is excluded.'}else{$ratio=$info.Width/[math]::Max(1,$info.Height);$low=$info.Width-lt 1920-or$info.Height-lt 1080;$off=[math]::Abs($ratio-(16/9))-gt .02;$eligible=$low-or$off;$reason=if($off){'Static background is not 16:9 and needs fit review.'}elseif($low){'Static background is below 1920 x 1080 and needs quality review.'}else{'Static background meets the 1920 x 1080 16:9 baseline.'}}}}}
 $srcRel=if($path){Rel $song.FullName $path}else{$null};$srcHash=if($path){Hash $path}else{$null};$raw=@($relative,($parts-join'|'),$ref,$srcRel,$srcHash,$reason)-join"`n";$sha=[Security.Cryptography.SHA256]::Create();try{$fp=([BitConverter]::ToString($sha.ComputeHash([Text.Encoding]::UTF8.GetBytes($raw)))).Replace('-','')}finally{$sha.Dispose()}
 [ordered]@{songPath=$relative;fingerprint=$fp;simfiles=@($parts|ForEach-Object{$n,$h=$_-split':',2;[ordered]@{path=$n;sha256=$h}});backgroundReference=$ref;sourcePath=$srcRel;sourceSha256=$srcHash;sourceWidth=if($info){$info.Width}else{$null};sourceHeight=if($info){$info.Height}else{$null};sourceFrames=if($info){$info.Frames}else{$null};observedAt=$now;assessedAt=$now;eligible=$eligible;reason=$reason;status=if($eligible){'eligible'}else{'ineligible'};processedAt=$null;lastAttemptedAt=$null;pendingAction=$null;previewPath=$null;previewSha256=$null;attemptHistory=@();decisionHistory=@()}
}
$pack=(Resolve-Path -LiteralPath $PackPath).Path;$file=[IO.Path]::GetFullPath($QueuePath);$doc=if(Test-Path -LiteralPath $file){Get-Content -LiteralPath $file -Raw|ConvertFrom-Json}else{[pscustomobject]@{schemaVersion=1;packPath='C:\Games\ITGmania\Songs\Misc. Collected';generatedAt=$null;songs=@()}}
if($Refresh){$now=(Get-Date).ToUniversalTime().ToString('o');$old=@{};foreach($x in @($doc.songs)){$old[$x.songPath]=$x};$songs=@();$changed=$false;foreach($dir in Get-ChildItem -LiteralPath $pack -Directory|Sort-Object Name){$fresh=Assess $dir $pack $now;$prior=$old[$fresh.songPath];if($prior-and$prior.fingerprint-eq$fresh.fingerprint){if($prior.status-notin$statuses){throw "Invalid status: $($prior.status)"};$songs+=$prior}elseif($prior-and$prior.status-eq'installed'-and$prior.previewSha256-and$prior.previewSha256-eq$fresh.sourceSha256){$fresh.status='installed';$fresh.eligible=$false;$fresh.reason='Current source exactly matches the previously approved installed preview.';$fresh.processedAt=$prior.processedAt;$fresh.lastAttemptedAt=$prior.lastAttemptedAt;$fresh.previewPath=$prior.previewPath;$fresh.previewSha256=$prior.previewSha256;$fresh.attemptHistory=@($prior.attemptHistory);$fresh.decisionHistory=@($prior.decisionHistory);$songs+=[pscustomobject]$fresh;$changed=$true}else{$songs+=[pscustomobject]$fresh;$changed=$true}};if(@($doc.songs).Count-ne$songs.Count){$changed=$true};if($changed){$learning=if($doc.PSObject.Properties.Name-contains'learningHistory'){@($doc.learningHistory)}else{@()};$doc=[pscustomobject][ordered]@{schemaVersion=1;packPath='C:\Games\ITGmania\Songs\Misc. Collected';generatedAt=$now;songs=$songs;learningHistory=$learning};WriteDoc $doc $file}}
function Exact(){if(-not$SongPath-or-not$Fingerprint){throw 'SongPath and Fingerprint are required.'};$m=@($doc.songs|Where-Object{$_.songPath-eq$SongPath-and$_.fingerprint-eq$Fingerprint});if($m.Count-ne 1){throw 'Exact current fingerprint not found.'};$m[0]}
if($SetStatus){$r=Exact;if($SetStatus-eq'pending'-and$r.status-notin@('eligible','pending')){throw 'Only eligible content can become pending.'};if($SetStatus-in@('installed','denied')-and$r.status-ne'pending'){throw 'Only pending content can receive an install or denial decision.'};if($SetStatus-eq'skipped'-and$r.status-notin@('eligible','pending')){throw 'Only eligible or pending content can be skipped.'};if($SetStatus-in@('installed','denied','skipped')-and[string]::IsNullOrWhiteSpace($DecisionNote)){throw 'DecisionNote is required.'};if($PreviewPath){$p=(Resolve-Path -LiteralPath $PreviewPath).Path;$r.previewPath=$p;$r.previewSha256=Hash $p};if($SetStatus-in@('installed','denied')-and-not$r.previewSha256){throw 'A bound preview is required.'};$now=(Get-Date).ToUniversalTime().ToString('o');$r.status=$SetStatus;$r.processedAt=if($SetStatus-eq'eligible'){$null}else{$now};if($SetStatus-eq'pending'){$r.lastAttemptedAt=$now};$r.pendingAction=if($SetStatus-eq'pending'-and$r.previewSha256){'awaiting-install-decision'}elseif($SetStatus-eq'pending'){'generate-preview'}else{$null};if($SetStatus-in@('installed','denied','skipped')){$r.decisionHistory=@($r.decisionHistory)+[pscustomobject][ordered]@{recordedAt=$now;outcome=$SetStatus;note=$DecisionNote.Trim();previewPath=$r.previewPath;previewSha256=$r.previewSha256}};$doc.generatedAt=$now;WriteDoc $doc $file}
if($ReturnToQueue){if($SetStatus){throw 'Cannot combine ReturnToQueue and SetStatus.'};$r=Exact;if($r.status-ne'pending'){throw 'Only pending content can be returned.'};if(-not$AttemptOutcome-or[string]::IsNullOrWhiteSpace($AttemptNote)){throw 'AttemptOutcome and AttemptNote are required.'};$now=(Get-Date).ToUniversalTime().ToString('o');$r.attemptHistory=@($r.attemptHistory)+[pscustomobject][ordered]@{recordedAt=$now;outcome=$AttemptOutcome;note=$AttemptNote.Trim();discardedPreviewPath=$r.previewPath;discardedPreviewSha256=$r.previewSha256};$r.lastAttemptedAt=$now;$r.status='eligible';$r.processedAt=$null;$r.pendingAction=$null;$r.previewPath=$null;$r.previewSha256=$null;$doc.generatedAt=$now;WriteDoc $doc $file}
if($SelectNext){$n=@($doc.songs|Where-Object{$_.eligible-and$_.status-eq'eligible'}|Sort-Object @{Expression={if($_.lastAttemptedAt){1}else{0}}},@{Expression={if($_.lastAttemptedAt){[datetime]$_.lastAttemptedAt}else{[datetime]::MinValue}}},@{Expression={[datetime]$_.observedAt}},songPath|Select-Object -First 1);if($n.Count){$n[0]|ConvertTo-Json -Depth 10}else{[pscustomobject]@{result='no-candidates'}|ConvertTo-Json}}else{$counts=@($doc.songs)|Group-Object status|Sort-Object Name|ForEach-Object{[pscustomobject]@{status=$_.Name;count=$_.Count}};[pscustomobject]@{queuePath=$file;total=@($doc.songs).Count;counts=$counts}|ConvertTo-Json -Depth 4}
